### ISSUE TITLE
Switch is not deleted

### ISSUE THREAD

**Issue by oigroigm** [Martvvliet/homebridge-denon-heos#10]
The switch is not deleted in the Home app after deleting it from the configuration file

**Comment by Martvvliet** [comment]
Yes this is due to the way i had to integrate the separate switches. Still a bug which i will fix soon. You can work around it by removing cached accessories for now. Sorry

**Comment by Martvvliet** [comment]
In the last update, this issue should be fixed. Can you confirm this?

**Comment by Caban-ru** [comment]
got this error after adding switches 

[2020-1-27 19:32:19] TypeError: Cannot read property 'includes' of undefined
    at discover.setDenonInformation (/usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:144:36)
    at legacyClient.setupLegacyService (/usr/local/lib/node_modules/homebridge-denon-heos/index.js:638:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
[2020-1-27 19:32:19] Got SIGTERM, shutting down Homebridge...
[2020-1-27 19:32:19] TypeError: Cannot read property 'includes' of undefined
    at discover.setDenonInformation (/usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:144:36)
    at legacyClient.setupLegacyService (/usr/local/lib/node_modules/homebridge-denon-heos/index.js:638:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    at listOnTimeoutNT (timers.js:369:26)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Martvvliet** [comment]
Hmm I see, this issue shouldn't come forward, as it means that the received auto-discovered port is not correct, but anyway I made sure that it won't crash the software anymore. You can update to 2.0.8 with the fix.
What type of receiver do you have?

**Comment by Caban-ru** [comment]
still not ok,
I have X4300H

this is main config, that works ok 
` {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "192.168.100.7",
                    "switchInfoMenu": false,
                    "port": 8080,
                    "inputs": [
                        {
                            "inputID": "TV",
                            "name": "TV"
                        },
                        {
                            "inputID": "NET",
                            "name": "Online Radio"
                        }
                    ]
                }
            ]
        }`

Now, whan i Adding switches & restart HB - looks ok, no errors
but switches not appearing in HomeKit
& Denon receiver (and other devices from this HB instance) becomes "Not responding" in HomeKit..

After removing switches & restarting HB - other devices becomes ok, but not receiver (still not responding)

After Power off/on Receiver & restarting HB, receiver coming back to HomeKit

this is my switches code:
`           "switches": [
                {
                    "name": "AVR TV input",
                    "ip": "192.168.100.7",
                    "port": 8080,
                    "inputID": "TV",
                    "pollAllInput": false
                },
                {
                    "name": "AVR Online input",
                    "ip": "192.168.100.7",
                    "port": 8080,
                    "inputID": "NET",
                    "pollAllInput": false
                }
            ]
`

**Comment by Martvvliet** [comment]
Hmm thats weird. Do you see a recognised receiver in your Log? And can you try to start homebridge with -D enabled so you can see the debug log?

**Comment by Caban-ru** [comment]
> Hmm thats weird. Do you see a recognised receiver in your Log? And can you try to start homebridge with -D enabled so you can see the debug log?

Stopped Homebridge @ 5.
Starting Homebridge @ 5...
Started Homebridge @ 5.
[2020-1-28 16:00:15] Loaded config.json with 0 accessories and 2 platforms.
[2020-1-28 16:00:15] ---
[2020-1-28 16:00:15] Loaded plugin: homebridge-config-ui-x
[2020-1-28 16:00:15] Registering platform 'homebridge-config-ui-x.config'
[2020-1-28 16:00:15] ---
[2020-1-28 16:00:15] Loaded plugin: homebridge-denon-heos
[2020-1-28 16:00:15] Registering platform 'hombridge-denon-heos.DenonAVR'
[2020-1-28 16:00:15] ---
[2020-1-28 16:00:15] Loading 2 platforms...
[2020-1-28 16:00:15] [DenonAVR] Initializing DenonAVR platform...
2020-01-28T15:00:15.969Z node-ssdp:client discovering all IPs from interface lo
2020-01-28T15:00:15.969Z node-ssdp:client discovering all IPs from interface eth0
2020-01-28T15:00:15.970Z node-ssdp:client Will use interface eth0
[2020-1-28 16:00:15] [Config] Initializing config platform...
[2020-1-28 16:00:15] [Config] Running in Standalone Mode.
[2020-1-28 16:00:15] Loading 0 accessories...
Setup Payload:
X-HM://0023IU0PLAAAN
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                         
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐
    │ 031-94-137 │
    └────────────┘
                       
[2020-1-28 16:00:16] [DenonAVR] DidFinishLaunching
[2020-1-28 16:00:18] Denon Receiver is running on port 43263.
[2020-1-28 16:00:18] Please add [Denon Receiver] manually in Home app. Setup Code: 031-94-137

____________________________
This is config 
 {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "192.168.100.7",
                    "switchInfoMenu": false,
                    "port": 8080,
                    "inputs": [
                        {
                            "inputID": "TV",
                            "name": "TV"
                        },
                        {
                            "inputID": "NET",
                            "name": "Online Radio"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "AVR TV input",
                    "ip": "192.168.100.7",
                    "port": 8080,
                    "inputID": "TV",
                    "pollAllInput": false
                },
                {
                    "name": "AVR Online input",
                    "ip": "192.168.100.7",
                    "port": 8080,
                    "inputID": "NET",
                    "pollAllInput": false
                }
            ]
        },

**RESULT:
Receiver "Not responding" in HomeKit
no switches in HomeKit**

**Comment by oigroigm** [comment]
try  "port": "8080"

**Comment by Caban-ru** [comment]
> try "port": "8080"

no result

**Comment by Martvvliet** [comment]
> try "port": "8080"

This is fixed in the latest version :)

**Comment by Martvvliet** [comment]
@Caban-ru. Is that log complete? After the init phase some other things should be logged. Can you try it with Debug on and add to your config file the variable “ debugTrace” and set it to true? So start with; DEBUG=* homebridge -D. You should see some other log information. Mine is running stable for many days already so not sure what is going wrong at your place.

**Comment by Caban-ru** [comment]
with DEBUG=* this is all information from your plugin (

where to put debugTrace? If like this - nothing changed

          "platform": "DenonAVR",
            "pollInterval": 3,
            "debugTrace": true,
            "devices": [

**Comment by Martvvliet** [comment]
You are missing the -D. The whole command to start homebridge is `DEBUG=* homebridge -D`. About the debugTrace, I forgot that it was already true as default so you can leave that out.

**Comment by Caban-ru** [comment]
> @Caban-ru. Is that log complete? After the init phase some other things should be logged. Can you try it with Debug on and add to your config file the variable “ debugTrace” and set it to true? So start with; DEBUG=* homebridge -D. You should see some other log information. Mine is running stable for many days already so not sure what is going wrong at your place.

Loading logs using "systemd" method...
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge@5

Starting Homebridge @ 5...
Started Homebridge @ 5.
[2020-1-28 19:45:07] Loaded config.json with 1 accessories and 2 platforms.
[2020-1-28 19:45:08] ---
[2020-1-28 19:45:08] Loaded plugin: homebridge-config-ui-x
[2020-1-28 19:45:08] Registering platform 'homebridge-config-ui-x.config'
[2020-1-28 19:45:08] ---
[2020-1-28 19:45:11] Loaded plugin: homebridge-denon-heos
[2020-1-28 19:45:11] Registering platform 'hombridge-denon-heos.DenonAVR'
[2020-1-28 19:45:11] ---
[2020-1-28 19:45:18] Loaded plugin: homebridge-mqttthing
[2020-1-28 19:45:18] Registering accessory 'homebridge-mqttthing.mqttthing'
[2020-1-28 19:45:18] ---
[2020-1-28 19:45:18] Loading 2 platforms...
[2020-1-28 19:45:18] [DenonAVR] Initializing DenonAVR platform...
2020-01-28T18:45:18.756Z node-ssdp:client discovering all IPs from interface lo
2020-01-28T18:45:18.758Z node-ssdp:client discovering all IPs from interface eth0
2020-01-28T18:45:18.758Z node-ssdp:client Will use interface eth0
[2020-1-28 19:45:18] [Config] Initializing config platform...
[2020-1-28 19:45:18] [Config] Running in Standalone Mode.
[2020-1-28 19:45:18] Loading 1 accessories...
[2020-1-28 19:45:18] [Тест 1] Initializing mqttthing accessory...
[2020-1-28 19:45:18] [Тест 1] MQTT options: {"keepalive":30,"clientId":"mqttthing_ 1_ae5481af","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"rejectUnauthorized":false}
[2020-1-28 19:45:19] [DenonAVR] configureAccessory
Setup Payload:
X-HM://0023IU0PLAAAN
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                  
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐
    │ 031-94-137 │
    └────────────┘
                       
[2020-1-28 19:45:19] [DenonAVR] DidFinishLaunching
2020-01-28T18:45:19.193Z node-ssdp:client SSDP listening: { address: 'http://0.0.0.0:58751', interface: '192.168.100.79' }
2020-01-28T18:45:19.198Z node-ssdp:client Attempting to send an M-SEARCH request
2020-01-28T18:45:19.200Z node-ssdp:client Sending a message to 239.255.255.250:1900
Tue, 28 Jan 2020 18:45:19 GMT EventedHTTPServer Server listening on port 51830
[2020-1-28 19:45:19] Homebridge is running on port 51830.
[2020-1-28 19:45:19] [DenonAVR] setupLegacyService
[2020-1-28 19:45:19] [DenonAVR] setupTvService
[2020-1-28 19:45:19] [DenonAVR] 192.168.100.17: http://192.168.100.17:60006/upnp/desc/aios_device/aios_device.xml
[2020-1-28 19:45:19] [DenonAVR] Receiver with IP 192.168.100.7 not yet ready.
[2020-1-28 19:45:19] [DenonAVR] TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:97:74
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:304:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:90:5)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
[2020-1-28 19:45:19] [Тест 1] Received MQTT: /home/door1/position/percent = 70
[2020-1-28 19:45:19] [DenonAVR] Receiver with IP 192.168.100.17 not yet ready.
[2020-1-28 19:45:19] [DenonAVR] TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:98:77
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:304:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-denon-heos/lib/discover.js:90:5)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
[2020-1-28 19:45:19] [DenonAVR] setupLegacyService
[2020-1-28 19:45:19] [DenonAVR] Error in discovered port number Error: TypeError: Cannot read property 'includes' of undefined
[2020-1-28 19:45:19] [DenonAVR] setupTvService
[2020-1-28 19:45:19] [DenonAVR] Error in discovered port number Error: TypeError: Cannot read property 'includes' of undefined
[2020-1-28 19:45:19] [DenonAVR] setupTvSpeakerService
[2020-1-28 19:45:19] [DenonAVR] setupInputSourcesService
[2020-1-28 19:45:19] [DenonAVR] publishExternalAccessories
Tue, 28 Jan 2020 18:45:19 GMT EventedHTTPServer Server listening on port 34947
[2020-1-28 19:45:19] Denon Receiver is running on port 34947.
[2020-1-28 19:45:19] Please add [Denon Receiver] manually in Home app. Setup Code: 031-94-137

[2020-1-28 19:45:22] [DenonAVR] checkReceiverState
[2020-1-28 19:45:22] [DenonAVR] updateReceiverStatus
2020-01-28T18:45:23.785Z node-ssdp:client Stopped socket on 192.168.100.79
[2020-1-28 19:45:24] [DenonAVR] removeCachedAccessory
[2020-1-28 19:45:25] [DenonAVR] pollForUpdates
[2020-1-28 19:45:25] [DenonAVR] checkReceiverState
[2020-1-28 19:45:25] [DenonAVR] updateReceiverStatus
[2020-1-28 19:45:28] [DenonAVR] pollForUpdates
[2020-1-28 19:45:28] [DenonAVR] checkReceiverState
[2020-1-28 19:45:28] [DenonAVR] updateReceiverStatus

**Comment by Caban-ru** [comment]
192.168.100.7 -  Denon receiver IP
192.168.100.17 - Denon Heos 1 speaker ip

ip 192.168.100.17 not used in Config

**Comment by Martvvliet** [comment]
Ok Thanks. It does discover the 17 but not the 7. Although after that, it should ignore the fact that it does not discover the receiver and start working with the manual port etc. It also looks that way as it polling for the receiver state. What happens when you let it run for 1-2 min (even though it is not working)? It might be saying in the debug log that it couldn't connect to your receiver. What you can try is typing the following in the browser: `http://192.168.100.7:8080/goform/formMainZone_MainZoneXmlStatusLite.xml` This should give the state of the receiver. What you can try is power cycle the receiver, so really unplug and replug. The receivers are sensitive to DDoS, and in the previous release, it was polling too many times at exactly the same time. This makes the HTML interface crash, so it won't work until you power cycle the receiver. It is sort of fixed in 2.0.8, but not very nice yet. I'm working on a more sophisticated polling method, but that's still in progress.

**Comment by Caban-ru** [comment]
I think device is always acessable over http
& no problems with denon ios app
this is result for http request right now (receiver is not responding in HomeKit)
http://192.168.100.7:8080/goform/formMainZone_MainZoneXmlStatusLite.xml

<item>
<Power>
<value>ON</value>
</Power>
<InputFuncSelect>
<value>NET</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-55.0</value>
</MasterVolume>
<Mute>
<value>on</value>
</Mute>
</item>

**Comment by Martvvliet** [comment]
Alright, that means that it is accessible indeed. I’m kinda out of clues. You can install the previous version which was working until I have solution or maybe an reset in cache accessories might help. Last question, does it work if you remove the switches and only use the TV service?

**Comment by Caban-ru** [comment]
> Alright, that means that it is accessible indeed. I’m kinda out of clues. You can install the previous version which was working until I have solution or maybe an reset in cache accessories might help. Last question, does it work if you remove the switches and only use the TV service?

it work if i remove switches & remove receiver from Homekit
& add receiver again (as TV to Homekit) and it's works fine !!Until first HB reboot
after reboot it's become "Not responding"

**Comment by Martvvliet** [comment]
Hmm. Just pushed an updated version with a central polling system. This should reduce the load on your pi and on the receiver. I also added some more log info etc. Maybe if you test this version it will work?

**Comment by oigroigm** [comment]
after updating the receivers they are not reachable from the home app while the tiles have disappeared in the homebridge

**Comment by Martvvliet** [comment]
Did it work with the previous version 2.0.8?
Can you run it for me with the -D option turned on so you get debug logs in your homebridge logs? and if you can post the log of around 30 seconds running? I have it stable at home with four switches and one tv accessory on a RPi with many more plugins running. I'm really curious why it is not working in your configuration.

**Comment by oigroigm** [comment]
with the previous version everything worked, now I have removed the plugins, I will do more tests later

**Comment by Martvvliet** [comment]
Hmm ok, please let me know. You can always install a previous version if you put after the install command @2.0.8

**Comment by Caban-ru** [comment]
> with the previous version everything worked, now I have removed the plugins, I will do more tests later

did it work after rebooting Homebridge?  I mean 2.0.8 & 2.09

**Comment by Caban-ru** [comment]
> Hmm ok, please let me know. You can always install a previous version if you put after the install command @2.0.8

tried many times 2.0.8 & 2.0.9
they are not working for me

I'll stay at 2.0.6,  it's stable version (but without switches)
I realised, I don't need this switches. I can change input by automation&shortcut

**Comment by Martvvliet** [comment]
@Caban-ru and @oigroigm. Found a bug that made the receiver disappear. Sorry for inconvenience. It should be fixed in 2.1.1.

**Comment by Caban-ru** [comment]
just tested 2.1.1
receiver now fine) works after restart as well

about switches:
I can see them in HB web ui (and they works), but they are not appearing in HomeKit

**Comment by Martvvliet** [comment]
Ok good that it is working again. Thank you for testing. I'm not sure why it is not appearing in Homekit but is in the web UI. What I can think of is removing the Homebridge from the Home app and after removing the persist and accesories folder, readding. This is the only thing I can think of. You will have to setup all other plugins too in the home app though :/

**Comment by Martvvliet** [comment]
@oigroigm Do you still have issues in the latest version?

**Comment by oigroigm** [comment]
I installed the latest version but hombrige crashes

**Comment by Martvvliet** [comment]
@oigroigm Hmm. can you post your Homebridge log when you run it with debug enabled? If you don't know how that works, you can add the `"debugToInfo": true,` line to your config.json:
```json
"platforms": [{
    "platform": "DenonAVR",
    "debugToInfo": true,
    "devices": [{
```

**Comment by oigroigm** [comment]
[2/22/2020, 10:34:45 AM] [DenonAVR] DEBUG: pollForUpdates: 192.168.1.6
[2/22/2020, 10:34:46 AM] TypeError: Cannot read property '0' of undefined
    at /usr/lib/node_modules/homebridge-denon-heos/index.js:376:49
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:198:13)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/lib/node_modules/homebridge-denon-heos/index.js:370:6)
    at Request.self.callback (/usr/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
[2/22/2020, 10:34:46 AM] Got SIGTERM, shutting down Homebridge...
[2/22/2020, 10:34:48 AM] [DenonAVR] DEBUG: pollForUpdates: 192.168.1.6
[2/22/2020, 10:34:48 AM] TypeError: Cannot read property '0' of undefined
    at /usr/lib/node_modules/homebridge-denon-heos/index.js:376:49
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:198:13)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-denon-heos/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/lib/node_modules/homebridge-denon-heos/node_modules/xml2js/lib/parser.js:369:19)
    at Request._callback (/usr/lib/node_modules/homebridge-denon-heos/index.js:370:6)
    at Request.self.callback (/usr/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-denon-heos/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)

**Comment by Martvvliet** [comment]
Hmm. It looks like you get a different result from the status page.
Can you try to put the following line in your browser and post the result?
`http://192.168.1.6:8080/goform/formMainZone_MainZoneXmlStatusLite.xml` or `http://192.168.1.6:80/goform/formMainZone_MainZoneXmlStatusLite.xml`

**Comment by oigroigm** [comment]
<Power>
<value>STANDBY</value>
</Power>
<InputFuncSelect>
<value>AUXD</value>
</InputFuncSelect>
<MasterVolume>
<value>-60.0</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>

**Comment by Martvvliet** [comment]
Ok, clear. Apparently your receiver doesn't have the option to switch between relative and absolute volume display, so it misses that info too. This means that it was reading data that wasn't available. In 2.3.6 this should be fixed.

**Comment by oigroigm** [comment]
i tried the new version and it seems to work.

Thanks

**Comment by Martvvliet** [comment]
Great thanks for reporting. will close this issue. If there are other issues please let me know!
